config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    namespace :admin do
        root to: 'dashboard#index', as: 'dashboard'
        get 'dashboard/accounts', to: 'dashboard#accounts'
        get 'dashboard/online', to: 'dashboard#online'
        resources :users
    end
    match "*path", to: "pages#show", via: :all
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: "pages#index"


end

app/models/account_access.rb
# require Rails.root.join('lib', 'devise', 'encryptors', 'sha1')

class AccountAccess < AuthRecord
    self.table_name = 'account_access'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_record.rb
class AuthRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"auth_#{Rails.env}"
end

app/models/character.rb
class Character < CharactersRecord
    self.table_name = "characters"

    scope :online, -> { where(online: 1) }
    # alias_attribute :character_class, :class
    # self.ignored_columns = %w(class)
    # self.renamed_columns

    def class_name
        # 1 1   Warrior
        #  2   2   Paladin
        #  3   4   Hunter
        #  4   8   Rogue
        #  5   16  Priest
        #  6   32  Death Knight (3.x)
        #  7   64  Shaman
        #  8   128 Mage
        #  9   256 Warlock
        #  10  512 Monk (5.x)
        #  11  1024    Druid
        case attributes['class']
        when 1
            "Warrior"
        when 2
            "Paladin"
        when 3
            "Hunter"
        when 4
            "Rogue"
        when 5
            "Priest"
        when 6
            "Death Knight"
        when 7
            "Shaman"
        when 8
            "Mage"
        when 9
            "Warlock"
        when 11
            "Druid"
        end
    end

    def race_name
        case race
        when 1
            "Human"
        when 2
            "Orc"
        when 3
            "Dwarf"
        when 4
            "Night Elf"
        when 5
            "Undead"
        when 6
            "Tauren"
        when 7
            "Gnome"
        when 8
            "Troll"
        when 10
            "Blood Elf"
        when 11
            "Draenei"
        end
    end
end

app/models/characters_record.rb
class CharactersRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"characters_#{Rails.env}"
end

app/models/page.rb
class Page < ApplicationRecord
    def content
        body
        @template ||= Liquid::Template.parse(body) # Parses and compiles the template
        # @template.registers["realms"] =
        @template.render().html_safe
    end
end

module PluralFilter
  def to_plural(count, word)
    puts "about to pluralize #{word}"
    word.pluralize(count)
  end
end

app/models/realm.rb
class Realm < AuthRecord
    self.table_name = "realmlist"
    def online
        @online ||= Character.where(online: 1).count
    end

    def to_hash
        {
            'name' => name,
            'online' => online
        }
    end
end

app/models/user.rb
# require Rails.root.join('lib', 'devise', 'encryptors', 'sha1')

class User < AuthRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :encryptable,
        :recoverable, :rememberable, :validatable, :encryptor => :sha1

    self.table_name = "account"
    has_many :account_accesses, foreign_key: :id
    has_many :characters, foreign_key: :account

    alias_attribute 'encrypted_password', 'sha_pass_hash'
    validates :username, presence: :true, uniqueness: { case_sensitive: true }, length: { maximum: 16}

    def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      username = conditions.delete(:username)
      where(conditions.to_h).where(username: username.upcase).first
    end

    def password_salt
      username
    end
    def password_salt= _a
    end

    def admin?
      gm_level == 3
    end

    def gm?
      gm_level > 0
    end

    def gm_level
      @gm_level ||= account_accesses.maximum(:gmlevel)
    end

    def online?
      characters.where(online: 1).any?
    end
end

app/controllers/admin/dashboard_controller.rb
module Admin
    class DashboardController < AdminController
        def index
            @online_characters = Character.online.paginate(page: params[:character_page] || 1, per_page: 25)
        end

        def accounts
            render json: {
                accounts: User.count,
                change: User.where("joindate > ?", 24.hours.ago).count
            }
        end

        def online
            render json: {
                online: Character.online.count,
            }
        end
    end
end

app/controllers/admin/users_controller.rb
module Admin
    class UsersController < AdminController
        def index
            @users = User.order(id: :asc).paginate(:page => params[:page] || 1)#.select('"users".*,')
            @character_counts = Character.group(:account).count
            @online = Character.select(:account).group(:account).where(online: 1).pluck(:account)
        end

        def show
            @user = User.find(params[:id])
        end
        # def collection

        # end

        # def model
        #     User.find(params[])
        # end
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_gm!
    layout 'admin/layouts/application'
    protected
    def authenticate_gm!
        redirect_to(new_user_session_path) unless current_user && current_user.gm?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @realms = Realm.all
        @page = Page.find_by(slug: 'home')
        raise ActionController::RoutingError.new('Not Found') if @page.nil?
    end

      def show
        path = params[:path] || params[:name]
        puts "About to load #{path} page"
        @page = Page.find_by(slug: path)
        raise ActionController::RoutingError.new('Not Found') if @page.nil?
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pluralize_filter.rb
# module PluralizeFilter
#   def plural(count, word)
#     puts "about to pluralize #{word}"
#     word.pluralize(count)
#   end
# end

# Liquid::Template.register_filter(PluralizeFilter)

app/views/admin/_sidebar.html.erb
<!-- #Left Sidebar ==================== -->
<div class="sidebar">
  <div class="sidebar-inner">
    <!-- ### $Sidebar Header ### -->
    <div class="sidebar-logo">
      <div class="peers ai-c fxw-nw">
        <div class="peer peer-greed">
          <a class="sidebar-link td-n" href="<%= root_path %>">
            <div class="peers ai-c fxw-nw">
              <div class="peer">
                <div class="logo">
                  <img src="<%= asset_path("icon.png") %>" alt="">
                </div>
              </div>
              <div class="peer peer-greed">
                <h5 class="lh-1 mB-0 logo-text">Fallen Realms</h5>
              </div>
            </div>
          </a>
        </div>
        <div class="peer">
          <div class="mobile-toggle sidebar-toggle">
            <a href="" class="td-n">
              <i class="ti-arrow-circle-left"></i>
            </a>
          </div>
        </div>
      </div>
    </div>

    <!-- ### $Sidebar Menu ### -->
    <ul class="sidebar-menu scrollable pos-r">
      <li class="nav-item mT-30 active">
        <a class="sidebar-link" href="<%= admin_dashboard_path %>">
          <span class="icon-holder">
            <i class="c-blue-500 ti-home"></i>
          </span>
          <span class="title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
          <%= link_to admin_users_path do %>
          <span class="icon-holder">
            <i class="c-brown-500 ti-user"></i>
          </span>
          <span class="title">Users</span>
          <%- end %>
      </li>
      <!--
      <li class="nav-item">
        <a class='sidebar-link' href="compose.html">
          <span class="icon-holder">
            <i class="c-blue-500 ti-share"></i>
          </span>
          <span class="title">Compose</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="calendar.html">
          <span class="icon-holder">
            <i class="c-deep-orange-500 ti-calendar"></i>
          </span>
          <span class="title">Calendar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="chat.html">
          <span class="icon-holder">
            <i class="c-deep-purple-500 ti-comment-alt"></i>
          </span>
          <span class="title">Chat</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="charts.html">
          <span class="icon-holder">
            <i class="c-indigo-500 ti-bar-chart"></i>
          </span>
          <span class="title">Charts</span>
        </a>
      </li>
      <li class="nav-item">
        <a class='sidebar-link' href="forms.html">
          <span class="icon-holder">
            <i class="c-light-blue-500 ti-pencil"></i>
          </span>
          <span class="title">Forms</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="sidebar-link" href="ui.html">
          <span class="icon-holder">
              <i class="c-pink-500 ti-palette"></i>
            </span>
          <span class="title">UI Elements</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-orange-500 ti-layout-list-thumb"></i>
          </span>
          <span class="title">Tables</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class='sidebar-link' href="basic-table.html">Basic Table</a>
          </li>
          <li>
            <a class='sidebar-link' href="datatable.html">Data Table</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
              <i class="c-purple-500 ti-map"></i>
            </span>
          <span class="title">Maps</span>
          <span class="arrow">
              <i class="ti-angle-right"></i>
            </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="google-maps.html">Google Map</a>
          </li>
          <li>
            <a href="vector-maps.html">Vector Map</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
              <i class="c-red-500 ti-files"></i>
            </span>
          <span class="title">Pages</span>
          <span class="arrow">
              <i class="ti-angle-right"></i>
            </span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a class='sidebar-link' href="blank.html">Blank</a>
          </li>
          <li>
            <a class='sidebar-link' href="404.html">404</a>
          </li>
          <li>
            <a class='sidebar-link' href="500.html">500</a>
          </li>
          <li>
            <a class='sidebar-link' href="signin.html">Sign In</a>
          </li>
          <li>
            <a class='sidebar-link' href="signup.html">Sign Up</a>
          </li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="dropdown-toggle" href="javascript:void(0);">
          <span class="icon-holder">
            <i class="c-teal-500 ti-view-list-alt"></i>
          </span>
          <span class="title">Multiple Levels</span>
          <span class="arrow">
            <i class="ti-angle-right"></i>
          </span>
        </a>
        <ul class="dropdown-menu">
          <li class="nav-item dropdown">
            <a href="javascript:void(0);">
              <span>Menu Item</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a href="javascript:void(0);">
              <span>Menu Item</span>
              <span class="arrow">
                <i class="ti-angle-right"></i>
              </span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="javascript:void(0);">Menu Item</a>
              </li>
              <li>
                <a href="javascript:void(0);">Menu Item</a>
              </li>
            -->
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/admin/_top_bar.html.erb
<!-- ### $Topbar ### -->
<div class="header navbar">
  <div class="header-container">
   <!--  <ul class="nav-left">
      <li>
        <a id='sidebar-toggle' class="sidebar-toggle" href="javascript:void(0);">
          <i class="ti-menu"></i>
        </a>
      </li>
      <li class="search-box">
        <a class="search-toggle no-pdd-right" href="javascript:void(0);">
          <i class="search-icon ti-search pdd-right-10"></i>
          <i class="search-icon-close ti-close pdd-right-10"></i>
        </a>
      </li>
      <li class="search-input">
        <input class="form-control" type="text" placeholder="Search...">
      </li>
    </ul> -->
    <ul class="nav-right">
      <!--
      <li class="notifications dropdown">
        <span class="counter bgc-red">3</span>
        <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
          <i class="ti-bell"></i>
        </a>
        <ul class="dropdown-menu">
          <li class="pX-20 pY-15 bdB">
            <i class="ti-bell pR-10"></i>
            <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
          </li>
          <li>
            <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <span>
                      <span class="fw-500">John Doe</span>
                      <span class="c-grey-600">liked your <span class="text-dark">post</span>
                      </span>
                    </span>
                    <p class="m-0">
                      <small class="fsz-xs">5 mins ago</small>
                    </p>
                  </div>
                </a>
              </li>
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <span>
                      <span class="fw-500">Moo Doe</span>
                      <span class="c-grey-600">liked your <span class="text-dark">cover image</span>
                      </span>
                    </span>
                    <p class="m-0">
                      <small class="fsz-xs">7 mins ago</small>
                    </p>
                  </div>
                </a>
              </li>
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <span>
                      <span class="fw-500">Lee Doe</span>
                      <span class="c-grey-600">commented on your <span class="text-dark">video</span>
                      </span>
                    </span>
                    <p class="m-0">
                      <small class="fsz-xs">10 mins ago</small>
                    </p>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          <li class="pX-20 pY-15 ta-c bdT">
            <span>
              <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a>
            </span>
          </li>
        </ul>
      </li>
    -->
    <!--
      <li class="notifications dropdown">
        <span class="counter bgc-blue">3</span>
        <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
          <i class="ti-email"></i>
        </a>

        <ul class="dropdown-menu">
          <li class="pX-20 pY-15 bdB">
            <i class="ti-email pR-10"></i>
            <span class="fsz-sm fw-600 c-grey-900">Emails</span>
          </li>
          <li>
            <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <div>
                      <div class="peers jc-sb fxw-nw mB-5">
                        <div class="peer">
                          <p class="fw-500 mB-0">John Doe</p>
                        </div>
                        <div class="peer">
                          <small class="fsz-xs">5 mins ago</small>
                        </div>
                      </div>
                      <span class="c-grey-600 fsz-sm">
                        Want to create your own customized data generator for your app...
                      </span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <div>
                      <div class="peers jc-sb fxw-nw mB-5">
                        <div class="peer">
                          <p class="fw-500 mB-0">Moo Doe</p>
                        </div>
                        <div class="peer">
                          <small class="fsz-xs">15 mins ago</small>
                        </div>
                      </div>
                      <span class="c-grey-600 fsz-sm">
                        Want to create your own customized data generator for your app...
                      </span>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="" class='peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100'>
                  <div class="peer mR-15">
                    <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                  </div>
                  <div class="peer peer-greed">
                    <div>
                      <div class="peers jc-sb fxw-nw mB-5">
                        <div class="peer">
                          <p class="fw-500 mB-0">Lee Doe</p>
                        </div>
                        <div class="peer">
                          <small class="fsz-xs">25 mins ago</small>
                        </div>
                      </div>
                      <span class="c-grey-600 fsz-sm">
                        Want to create your own customized data generator for your app...
                      </span>
                    </div>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          <li class="pX-20 pY-15 ta-c bdT">
            <span>
              <a href="email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email <i class="fs-xs ti-angle-right mL-10"></i></a>
            </span>
          </li>
        </ul>
      </li>
    -->
      <li class="dropdown">
        <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
          <div class="peer">
            <span class="fsz-sm c-grey-900"><%= current_user.username %></span>
          </div>
        </a>
        <ul class="dropdown-menu fsz-sm">
          <li>
            <%= link_to edit_user_registration_path, class: 'd-b td-n pY-5 bgcH-grey-100 c-grey-700' do %>
              <i class="ti-settings mR-10"></i>
              <span>Setting</span>
            <%- end %>
          </li>
          <!-- <li>
            <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
              <i class="ti-user mR-10"></i>
              <span>Profile</span>
            </a>
          </li> -->
          <!-- <li>
            <a href="email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
              <i class="ti-email mR-10"></i>
              <span>Messages</span>
            </a>
          </li> -->
          <li role="separator" class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, :method=>'delete', class: "d-b td-n pY-5 bgcH-grey-100 c-grey-700" do %>
              <i class="ti-power-off mR-10"></i>
              <span>Logout</span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <link rel="icon" type="image/png" href="<%= asset_path('icon.png') %>" />
    <style>
      #loader {
        transition: all 0.3s ease-in-out;
        opacity: 1;
        visibility: visible;
        position: fixed;
        height: 100vh;
        width: 100%;
        background: #fff;
        z-index: 90000;
      }

      #loader.fadeOut {
        opacity: 0;
        visibility: hidden;
      }

      .spinner {
        width: 40px;
        height: 40px;
        position: absolute;
        top: calc(50% - 20px);
        left: calc(50% - 20px);
        background-color: #333;
        border-radius: 100%;
        -webkit-animation: sk-scaleout 1.0s infinite ease-in-out;
        animation: sk-scaleout 1.0s infinite ease-in-out;
      }

      @-webkit-keyframes sk-scaleout {
        0% { -webkit-transform: scale(0) }
        100% {
          -webkit-transform: scale(1.0);
          opacity: 0;
        }
      }

      @keyframes sk-scaleout {
        0% {
          -webkit-transform: scale(0);
          transform: scale(0);
        } 100% {
          -webkit-transform: scale(1.0);
          transform: scale(1.0);
          opacity: 0;
        }
      }
    </style>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  </head>
  <body class="app">
    <!-- @TOC -->
    <!-- =================================================== -->
    <!--
      + @Page Loader
      + @App Content
          - #Left Sidebar
              > $Sidebar Header
              > $Sidebar Menu

          - #Main
              > $Topbar
              > $App Screen Content
    -->

    <!-- @Page Loader -->
    <!-- =================================================== -->
<!--     <div id='loader'>
      <div class="spinner"></div>
    </div>

    <script>
      window.addEventListener('load', () => {
        const loader = document.getElementById('loader');
        setTimeout(() => {
          loader.classList.add('fadeOut');
        }, 300);
      });
    </script> -->

    <!-- @App Content -->
    <!-- =================================================== -->
    <div>
      <%= render partial: 'sidebar' %>
      <!-- #Main ============================ -->
      <div class="page-container">
        <%= render partial: 'top_bar' %>
        <!-- ### $App Screen Content ### -->
        <main class='main-content bgc-grey-100'>
          <div id='mainContent'>
              <%= yield %>
          </div>
        </main>

        <!-- ### $App Screen Footer ### -->
        <footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
        </footer>
      </div>
    </div>

        <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
        <%= javascript_include_tag 'admin', 'data-turbolinks-track' => 'reload' %>
        <%- if content_for(:scripts) %>
          <script type="text/javascript">
            <%= yield :scripts %>
          </script>
        <%- end %>
  </body>
</html>

app/views/admin/users/index.html.erb
<table clas="table table-striped">
    <thead></thead>
    <tbody>
        <%- @users.each do |user| %>
            <tr>
                <td>
                    <%- if @online.include? user.id %>
                        <span class="icon-holder"><i class="c-green-500 ti-arrow-circle-up"></i></span>
                    <%- else %>
                        <span class="icon-holder"><i class="c-red-500 ti-arrow-circle-down"></i></span>
                    <%- end %>
                </td>
                <td><%= link_to user.username, [:admin, user] %></td>
                <td><%= @character_counts[user.id] %></td>
            </tr>
        <%- end %>
    </tbody>
</table>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/admin/users/show.html.erb
<div class="row gap-20 masonry pos-r">
    <div class="masonry-sizer col-md-6"></div>
    <h5>
        <%- if @user.online? %>
            <span class="icon-holder"><i class="c-green-500 ti-arrow-circle-up"></i></span>
        <%- else %>
            <span class="icon-holder"><i class="c-red-500 ti-arrow-circle-down"></i></span>
        <%- end %>
        <%= @user.username %>
    </h5>
    <hr />
    <div class="masonry-item col-12">
        <div class="bd bgc-white">
          <div class="peers fxw-nw@lg+ ai-s">
            <div class="peer peer-greed w-70p@lg+ w-100@lg- p-20">
              <div class="layers">
                <div class="layer w-100 mB-10">
                  <h6 class="lh-1">Characters</h6>
                </div>
                <div class="layer w-100">
                  <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Level</th>
                            <th>Name</th>
                            <th>Race</th>
                            <th>Class</th>
                        </tr>
                    </thead>
                    <%- @user.characters.each do |character| %>
                        <tr>
                            <td>
                                <%- if character.online? %>
                                    <span class="icon-holder"><i class="c-green-500 ti-arrow-circle-up"></i></span>
                                <%- else %>
                                    <span class="icon-holder"><i class="c-red-500 ti-arrow-circle-down"></i></span>
                                <%- end %>
                            </td>
                            <td><%= character.level %></td>
                            <td><%= character.name %></td>
                            <td><%= character.race_name %></td>
                            <td><%= character.class_name %></td>
                        </tr>
                    <%- end %>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "The Fallen Realms", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-links" aria-controls="nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="nav-links">
      <ul class="navbar-nav mr-auto">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
        <%- if current_user && current_user.gm? %>
            <li class="nav-item"><%= link_to 'Admin', admin_dashboard_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%- Page.where(show_in_nav: true).order(sort_order: :asc).each do |link| %>
    <li class='nav-item'><%= link_to link.nav_title, "/#{link.slug}", class: 'nav-link' %></li>
<%- end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "The Fallen Realms" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "The Fallen Realms" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<%= @page.content %>